### ISSUE TITLE
Go Get Errors

### ISSUE THREAD

**Issue by webRat** [markbates/buffalo#61]
Helping a friend/coworker setup for Gophercon tasks. The Gopheracademy gcon documentation says, `Start server by typing: buffalo dev`

I tracked buffalo to this repo. If I `go get` this repo, I'm presented with the following errors:

```
Raff-WBM:gcon raff$ go get github.com/markbates/buffalo
# github.com/markbates/buffalo/render
../../markbates/buffalo/render/render.go:38: undefined: inflect.Helpers
../../markbates/buffalo/render/template.go:32: undefined: "github.com/pkg/errors".WithMessage
../../markbates/buffalo/render/template.go:32: undefined: "github.com/pkg/errors".WithStack
../../markbates/buffalo/render/template.go:38: undefined: "github.com/pkg/errors".WithStack
../../markbates/buffalo/render/template.go:78: undefined: "github.com/pkg/errors".WithStack
../../markbates/buffalo/render/template.go:88: undefined: "github.com/pkg/errors".WithStack
```

Using `go get github.com/markbates/buffalo/...` doesn't fair any better and presents even more errors.

If I had to guess as to what the issue is, I think your inclusion of `"github.com/pkg/errors"` is being confused with `golang.org/pkg/errors`

Perhaps an alias would fix it? Or am I entirely wrong?

Thanks!

p.s. Yes, I did a `go get github.com/pkg/errors` to make sure it's on my system and findable within my gopath.

**Comment by markbates** [comment]
@webRat I just ran the following in a clean docker container:

```text
# go get github.com/markbates/buffalo/...
# cd /go/src
# buffalo new foo
Buffalo version 0.4.5

--> /go/src/foo/main.go
--> /go/src/foo/Procfile
--> /go/src/foo/Procfile.development
--> /go/src/foo/.buffalo.dev.yml
--> /go/src/foo/actions/app.go
--> /go/src/foo/actions/home.go
--> /go/src/foo/actions/home_test.go
--> /go/src/foo/actions/render.go
--> /go/src/foo/grifts/routes.go
--> /go/src/foo/templates/index.html
--> /go/src/foo/templates/application.html
--> /go/src/foo/assets/js/application.js
--> /go/src/foo/assets/css/application.css
--> /go/src/foo/.gitignore
--> go get github.com/markbates/refresh/...
--> go install github.com/markbates/refresh
--> go get github.com/markbates/grift/...
--> go install github.com/markbates/grift
--> /go/src/foo/assets/js/jquery.js
--> /go/src/foo/assets/js/jquery.map
--> /go/src/foo/assets/css/bootstrap.css
--> /go/src/foo/assets/js/bootstrap.js
--> /go/src/foo/assets/js/jquery.js
--> /go/src/foo/assets/js/jquery.map
--> /go/src/foo/models/models.go
--> go get github.com/markbates/pop/...
--> go install github.com/markbates/pop/soda
--> database.yml
--> go get -t ./...
--> gofmt -w .
```

and everything seemed to work just fine.

**Comment by markbates** [comment]
It feels like an environmental issue on you machine. You're missing several packages, based on your original issue.

What version of Go are you using? Maybe it's a problem with an old version of Go, but I doubt it. My gut says it's your ENV.

**Comment by webRat** [comment]
```
Raff-WBM:buffalo raff$ go version
go version go1.7rc6 darwin/amd64
```

**Comment by markbates** [comment]
lol! yeah, i would definitely suggest that. :)

**Comment by webRat** [comment]
I'm so used to using go in a docker container that I haven't upgraded my local machine in forever. Let me upgrade and report back. Sorry for the run around.

**Comment by webRat** [comment]
I upgraded and restarted my machine for good measure.

I blew away the existing `github.com/markbates` and `github.com/pkg`. I did the following:

```
Raff-WBM:github.com raff$ go get github.com/markbates/buffalo/...
# github.com/mattn/go-sqlite3
mattn/go-sqlite3/sqlite3-binding.c:20515:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here
```

That being said, I typed `buffalo` and finally got a working command prompt. So, I'll close this, since the error above is a warning. ¯\_(ツ)_/¯

**Comment by markbates** [comment]
Yay!
